import {GAME_RULES} from './rules.js';
export function createPhysics({Matter,engine,world,onCollision}){
 const {Bodies,World,Events}=Matter;let W=innerWidth,H=innerHeight,slotY=1,slotWidth=1,boss=null,pins=[],bounds=[];
 const clear=()=>{for(const body of [...bounds,...pins,boss].filter(Boolean))World.remove(world,body);bounds=[];pins=[];boss=null};
 function build(width,height){clear();W=Math.max(280,width);H=Math.max(480,height);bounds=[Bodies.rectangle(W/2,-30,W,60,{isStatic:true,label:'wall'}),Bodies.rectangle(-20,H/2,40,H,{isStatic:true,label:'wall'}),Bodies.rectangle(W+20,H/2,40,H,{isStatic:true,label:'wall'})];World.add(world,bounds);const r=Math.min(W*.12,GAME_RULES.boss.maxRadius);boss=Bodies.polygon(W/2,H*GAME_RULES.boss.yRatio,6,r,{isStatic:true,label:'boss',renderRadius:r,friction:0,frictionStatic:0});World.add(world,boss);const sy=Math.min((H*.32)/GAME_RULES.board.rows,65),start=H*.38;for(let row=0;row<GAME_RULES.board.rows;row++){const count=row%2===0?6:5,dx=W/(count+1);for(let col=1;col<=count;col++){const pin=Bodies.circle(dx*col,start+row*sy,GAME_RULES.board.pinBodyRadius,{isStatic:true,restitution:.68,friction:0,frictionStatic:0,label:'pin'});pin.plugin={...(pin.plugin||{}),pinId:`r${row}c${col}`};pins.push(pin)}}World.add(world,pins);slotWidth=W/5;slotY=H-GAME_RULES.board.slotBottom;for(let i=1;i<5;i++){const divider=Bodies.rectangle(i*slotWidth,slotY-28,GAME_RULES.board.dividerWidth,GAME_RULES.board.dividerHeight,{isStatic:true,friction:0,frictionStatic:0,label:'divider'});bounds.push(divider);World.add(world,divider)}const sensor=Bodies.rectangle(W/2,slotY+20,W,46,{isStatic:true,isSensor:true,label:'floorSensor'});bounds.push(sensor);World.add(world,sensor);return snapshot()}
 Events.on(engine,'collisionStart',onCollision);
 const snapshot=()=>({width:W,height:H,slotY,slotWidth,boss,pins});
 return{build,snapshot};
}
export function createFixedStepper(engine,Matter){let last=performance.now(),acc=0;const STEP=1000/60,MAX_DELTA=100;return now=>{const delta=Math.min(MAX_DELTA,Math.max(0,now-last));last=now;acc+=delta;let steps=0;while(acc>=STEP&&steps<6){Matter.Engine.update(engine,STEP);acc-=STEP;steps++}}}
