import {createBallWatchdog} from './ball-watchdog.js';
import {createBallTelemetry} from './ball-telemetry.js';
import {createPinDeflector} from './pin-deflector.js';
import {createPhysics,createFixedStepper} from './physics.js';
import {GAME_RULES,slotIndex,slotPoints} from './rules.js';
const {Engine,World,Bodies,Body}=Matter;
export function createGameRuntime(){
 let W=innerWidth,H=innerHeight,audioCtx=null,ballSeq=0,bossHp=GAME_RULES.boss.maxHp;const engine=Engine.create({gravity:{x:0,y:GAME_RULES.gravity,scale:.001}}),world=engine.world,canvas=document.getElementById('fx-canvas'),ctx=canvas.getContext('2d'),balls=[],particles=[],scores={},telemetry=createBallTelemetry();
 const audit=(b,event,data={})=>telemetry.push(b,event,data);
 const sound=t=>{if(!audioCtx||audioCtx.state==='suspended')return;try{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.connect(g);g.connect(audioCtx.destination);o.type=t==='boss_hit'?'sawtooth':t==='hit'?'triangle':'sine';o.frequency.setValueAtTime(t==='boss_hit'?120:t==='hit'?360:400,n);o.frequency.exponentialRampToValueAtTime(t==='boss_hit'?40:t==='hit'?120:800,n+.1);g.gain.setValueAtTime(.12,n);g.gain.linearRampToValueAtTime(.01,n+.12);o.start(n);o.stop(n+.12)}catch{}};
 const spark=(x,y,color,count)=>{for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,r:Math.random()*2.5+1,color,a:1})};
 const toast=(text,color='#00f0ff')=>{const f=document.getElementById('toast-feed');if(!f)return;const e=document.createElement('div');e.className='toast-entry';e.style.borderLeftColor=color;e.textContent=text;f.appendChild(e);setTimeout(()=>e.remove(),4000)};
 function damage(dmg,user){bossHp=Math.max(0,bossHp-(Number(dmg)||0));const pct=bossHp/GAME_RULES.boss.maxHp*100;document.getElementById('boss-fill').style.width=pct+'%';document.getElementById('boss-hp').textContent=Math.ceil(pct)+'%';sound('boss_hit');const boss=physics.snapshot().boss;if(boss)particles.push({x:boss.position.x,y:boss.position.y,wave:true,r:15,color:'#ff0055',a:1});if(bossHp<=0){bossHp=GAME_RULES.boss.maxHp;document.getElementById('boss-fill').style.width='100%';document.getElementById('boss-hp').textContent='100%';toast(`💥 ${user} FINALIZOU O BOSS!`,'#ffe600');window.confetti?.({particleCount:100,spread:70,origin:{y:.3}})}}
 function finish(b){if(!b?.gameData||b.gameData.finished||!balls.includes(b))return false;const {slotWidth,slotY}=physics.snapshot(),i=slotIndex(b.position.x,W),pts=slotPoints(b.gameData.scoreValue,i);b.gameData.finished=true;b.gameData.slot=i;b.gameData.points=pts;audit(b,'slot',{slot:i,multiplier:GAME_RULES.slots[i],points:pts,durationMs:performance.now()-b.gameData.spawnedAt,pinHits:b.gameData.pinHits||0,deflections:b.gameData.deflections||0,stalls:b.gameData.stalls||0,lastPin:b.gameData.lastPin||null});scores[b.gameData.username]=(scores[b.gameData.username]||0)+pts;const slot=document.getElementById('slot-'+i);slot?.classList.add('active');setTimeout(()=>slot?.classList.remove('active'),200);const top=Object.entries(scores).sort((a,z)=>z[1]-a[1])[0]||['',0];document.getElementById('top-user').textContent=top[0]||'Aguardando drops...';document.getElementById('top-score').textContent=top[1].toLocaleString()+' PTS';spark((i+.5)*slotWidth,slotY,b.gameData.color,10);sound('score');World.remove(world,b);const n=balls.indexOf(b);if(n>=0)balls.splice(n,1);audit(b,'removed',{reason:'scored'});return true}
 const deflect=createPinDeflector({Matter,onDeflect:(ball,pin,data)=>audit(ball,'pin-deflect',{pin:pin.plugin?.pinId||pin.id,...data})});
 const physics=createPhysics({Matter,engine,world,onCollision:e=>e.pairs.forEach(p=>{const a=p.bodyA,b=p.bodyB,labels=[a.label,b.label],ball=a.label==='ball'?a:b;if(!labels.includes('ball'))return;if(labels.includes('pin')){const pin=a.label==='pin'?a:b;telemetry.pinHit(ball,pin);deflect(ball,pin);spark(pin.position.x,pin.position.y,'#00f0ff',3);sound('hit')}if(labels.includes('boss')&&ball.gameData)damage(ball.gameData.damage,ball.gameData.username);if(labels.includes('floorSensor'))finish(ball)})});
 function resize(){W=Math.max(280,innerWidth);H=Math.max(480,innerHeight);const d=devicePixelRatio||1;canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0);physics.build(W,H)}
 function drop(opts={}){const {username='Live',color='#00f0ff',radius=9,damage=15,scoreValue=5,density=.002}=opts,spread=W*GAME_RULES.ball.spawnSpread,x=W/2+(Math.random()*spread-spread/2),b=Bodies.circle(x,H*.15,radius,{restitution:GAME_RULES.ball.restitution,friction:GAME_RULES.ball.friction,frictionStatic:GAME_RULES.ball.frictionStatic,frictionAir:GAME_RULES.ball.frictionAir,density,label:'ball',slop:GAME_RULES.ball.slop,collisionFilter:{group:-1}});b.gameData={id:`ball-${++ballSeq}`,username,color,radius,damage,scoreValue,spawnedAt:performance.now(),finished:false,pinHits:0,deflections:0,stalls:0,lastPin:null};balls.push(b);World.add(world,b);audit(b,'spawn',{scoreValue,radius});return b}
 const watchdog=createBallWatchdog({Matter,world,balls,getBounds:()=>{const s=physics.snapshot();return{width:W,height:H,slotY:s.slotY}},onStall:(b,data)=>audit(b,'stall',data),onRemove:(b,reason)=>audit(b,'removed',{reason,durationMs:performance.now()-b.gameData.spawnedAt,pinHits:b.gameData.pinHits||0,lastPin:b.gameData.lastPin||null})}),step=createFixedStepper(engine,Matter);
 function draw(now=performance.now()){step(now);watchdog.tick(now);ctx.clearRect(0,0,W,H);const {boss,pins}=physics.snapshot();if(boss){Body.rotate(boss,.012);ctx.save();ctx.translate(boss.position.x,boss.position.y);ctx.rotate(boss.angle);ctx.fillStyle='rgba(255,0,85,.2)';ctx.strokeStyle='#ff0055';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<6;i++){const r=boss.renderRadius,t=Math.PI/3*i,x=r*Math.cos(t),y=r*Math.sin(t);i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}for(const p of pins){ctx.beginPath();ctx.arc(p.position.x,p.position.y,GAME_RULES.board.pinRadius,0,Math.PI*2);ctx.fillStyle='#00f0ff';ctx.fill()}for(const b of balls){ctx.beginPath();ctx.arc(b.position.x,b.position.y,b.gameData.radius,0,Math.PI*2);ctx.fillStyle=b.gameData.color;ctx.fill();ctx.font='bold 11px Rajdhani';ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText(b.gameData.username,b.position.x,b.position.y-b.gameData.radius-4)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];if(p.wave){p.r+=6;p.a-=.04;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.strokeStyle=p.color;ctx.globalAlpha=Math.max(0,p.a);ctx.stroke()}else{p.x+=p.vx;p.y+=p.vy;p.a-=.05;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(0,p.a);ctx.fill()}ctx.globalAlpha=1;if(p.a<=0)particles.splice(i,1)}requestAnimationFrame(draw)}
 const start=()=>{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();document.getElementById('start-overlay').style.display='none'};
 const reset=()=>{for(const b of [...balls])World.remove(world,b);balls.length=0;particles.length=0;Object.keys(scores).forEach(k=>delete scores[k]);telemetry.clear();bossHp=GAME_RULES.boss.maxHp;document.getElementById('boss-fill').style.width='100%';document.getElementById('boss-hp').textContent='100%';document.getElementById('top-user').textContent='Aguardando drops...';document.getElementById('top-score').textContent='0 PTS'};
 const getState=()=>{const top=Object.entries(scores).sort((a,z)=>z[1]-a[1])[0]||['',0];return{bossHp,bossMaxHp:GAME_RULES.boss.maxHp,bossPercent:Math.round(bossHp/GAME_RULES.boss.maxHp*100),activeBalls:balls.length,topUser:top[0],topScore:top[1],multipliers:[...GAME_RULES.slots],viewport:{width:W,height:H}}};
 const getBallAudit=()=>telemetry.snapshot();resize();draw();return{drop,reset,resize,getState,getBallAudit,start,toast};
}
