const {Engine,World,Bodies,Body,Events}=Matter;
import {createBallWatchdog} from './ball-watchdog.js';
export function createGameRuntime(){
 let W=innerWidth,H=innerHeight,audioCtx=null,ballSeq=0;const engine=Engine.create({gravity:{x:0,y:1.4,scale:.001}}),world=engine.world,canvas=document.getElementById('fx-canvas'),ctx=canvas.getContext('2d'),balls=[],particles=[],scores={},ballAudit=[];let bossMax=1200,bossHp=bossMax,boss=null,pins=[],bounds=[],slotWidth=1,slotY=1;const mult=[2,5,15,5,2];
 const audit=(b,event,data={})=>{if(!b?.gameData)return;const row={id:b.gameData.id,event,at:performance.now(),x:b.position.x,y:b.position.y,...data};ballAudit.push(row);if(ballAudit.length>500)ballAudit.splice(0,ballAudit.length-500)};
 const sound=t=>{if(!audioCtx||audioCtx.state==='suspended')return;try{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),n=audioCtx.currentTime;o.connect(g);g.connect(audioCtx.destination);o.type=t==='boss_hit'?'sawtooth':t==='hit'?'triangle':'sine';o.frequency.setValueAtTime(t==='boss_hit'?120:t==='hit'?360:400,n);o.frequency.exponentialRampToValueAtTime(t==='boss_hit'?40:t==='hit'?120:800,n+.1);g.gain.setValueAtTime(.12,n);g.gain.linearRampToValueAtTime(.01,n+.12);o.start(n);o.stop(n+.12)}catch{}};
 const spark=(x,y,color,count)=>{for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,r:Math.random()*2.5+1,color,a:1})};
 const toast=(text,color='#00f0ff')=>{const f=document.getElementById('toast-feed');if(!f)return;const e=document.createElement('div');e.className='toast-entry';e.style.borderLeftColor=color;e.textContent=text;f.appendChild(e);setTimeout(()=>e.remove(),4000)};
 function build(){for(const b of [...bounds,...pins,boss].filter(Boolean))World.remove(world,b);bounds=[];pins=[];boss=null;W=Math.max(280,innerWidth);H=Math.max(480,innerHeight);const d=devicePixelRatio||1;canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0);bounds=[Bodies.rectangle(W/2,-30,W,60,{isStatic:true}),Bodies.rectangle(-20,H/2,40,H,{isStatic:true}),Bodies.rectangle(W+20,H/2,40,H,{isStatic:true})];World.add(world,bounds);const r=Math.min(W*.12,45);boss=Bodies.polygon(W/2,H*.28,6,r,{isStatic:true,label:'boss',renderRadius:r});World.add(world,boss);const sy=Math.min((H*.32)/6,65),start=H*.38;for(let row=0;row<6;row++){const count=row%2===0?6:5,dx=W/(count+1);for(let col=1;col<=count;col++)pins.push(Bodies.circle(dx*col,start+row*sy,6,{isStatic:true,restitution:.9,friction:.01,label:'pin'}))}World.add(world,pins);slotWidth=W/5;slotY=H-180;for(let i=1;i<5;i++){const b=Bodies.rectangle(i*slotWidth,slotY-30,6,75,{isStatic:true,label:'divider'});bounds.push(b);World.add(world,b)}const sensor=Bodies.rectangle(W/2,slotY+15,W,40,{isStatic:true,isSensor:true,label:'floorSensor'});bounds.push(sensor);World.add(world,sensor)}
 function damage(dmg,user){bossHp=Math.max(0,bossHp-(Number(dmg)||0));const pct=bossHp/bossMax*100;document.getElementById('boss-fill').style.width=pct+'%';document.getElementById('boss-hp').textContent=Math.ceil(pct)+'%';sound('boss_hit');if(boss)particles.push({x:boss.position.x,y:boss.position.y,wave:true,r:15,color:'#ff0055',a:1});if(bossHp<=0){bossHp=bossMax;document.getElementById('boss-fill').style.width='100%';document.getElementById('boss-hp').textContent='100%';toast(`💥 ${user} FINALIZOU O BOSS!`,'#ffe600');window.confetti?.({particleCount:100,spread:70,origin:{y:.3}})}}
 function drop(opts={}){const {username='Live',color='#00f0ff',radius=9,damage=15,scoreValue=5,density=.002}=opts,b=Bodies.circle(W/2+(Math.random()*W*.4-W*.2),H*.15,radius,{restitution:.62,friction:.035,frictionAir:.012,density,label:'ball',slop:.08});b.gameData={id:`ball-${++ballSeq}`,username,color,radius,damage,scoreValue,spawnedAt:performance.now(),lastMovingAt:performance.now(),finished:false};balls.push(b);World.add(world,b);audit(b,'spawn');return b}
 function finish(b,source='unknown'){if(source!=='floorSensor'||!b?.gameData||b.gameData.finished||!balls.includes(b))return false;b.gameData.finished=true;const i=Math.min(Math.max(Math.floor(b.position.x/slotWidth),0),4),pts=b.gameData.scoreValue*mult[i];b.gameData.slot=i;b.gameData.points=pts;audit(b,'slot',{slot:i,multiplier:mult[i],points:pts});scores[b.gameData.username]=(scores[b.gameData.username]||0)+pts;const slot=document.getElementById('slot-'+i);slot?.classList.add('active');setTimeout(()=>slot?.classList.remove('active'),200);const top=Object.entries(scores).sort((a,z)=>z[1]-a[1])[0]||['',0];document.getElementById('top-user').textContent=top[0]||'Aguardando drops...';document.getElementById('top-score').textContent=top[1].toLocaleString()+' PTS';spark(b.position.x,slotY,b.gameData.color,10);sound('score');World.remove(world,b);const n=balls.indexOf(b);if(n>=0)balls.splice(n,1);audit(b,'removed',{reason:'scored'});return true}
 Events.on(engine,'collisionStart',e=>e.pairs.forEach(p=>{const a=p.bodyA,b=p.bodyB,labels=[a.label,b.label],ball=a.label==='ball'?a:b;if(labels.includes('ball')&&labels.includes('pin')){const pin=a.label==='pin'?a:b;spark(pin.position.x,pin.position.y,'#00f0ff',4);sound('hit')}if(labels.includes('ball')&&labels.includes('boss')&&ball.gameData)damage(ball.gameData.damage,ball.gameData.username);if(labels.includes('ball')&&labels.includes('floorSensor'))finish(ball,'floorSensor')}));
 const watchdog=createBallWatchdog({Matter,world,balls,getBounds:()=>({width:W,height:H,slotY})});
 function draw(now=performance.now()){Engine.update(engine,1000/60);watchdog.tick(now);ctx.clearRect(0,0,W,H);if(boss){Body.rotate(boss,.012);ctx.save();ctx.translate(boss.position.x,boss.position.y);ctx.rotate(boss.angle);ctx.fillStyle='rgba(255,0,85,.2)';ctx.strokeStyle='#ff0055';ctx.lineWidth=4;ctx.beginPath();for(let i=0;i<6;i++){const r=boss.renderRadius,t=Math.PI/3*i,x=r*Math.cos(t),y=r*Math.sin(t);i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}for(const p of pins){ctx.beginPath();ctx.arc(p.position.x,p.position.y,5,0,Math.PI*2);ctx.fillStyle='#00f0ff';ctx.fill()}for(const b of balls){ctx.beginPath();ctx.arc(b.position.x,b.position.y,b.gameData.radius,0,Math.PI*2);ctx.fillStyle=b.gameData.color;ctx.fill();ctx.font='bold 11px Rajdhani';ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText(b.gameData.username,b.position.x,b.position.y-b.gameData.radius-4)}for(let i=particles.length-1;i>=0;i--){const p=particles[i];if(p.wave){p.r+=6;p.a-=.04;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.strokeStyle=p.color;ctx.globalAlpha=Math.max(0,p.a);ctx.stroke()}else{p.x+=p.vx;p.y+=p.vy;p.a-=.05;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=p.color;ctx.globalAlpha=Math.max(0,p.a);ctx.fill()}ctx.globalAlpha=1;if(p.a<=0)particles.splice(i,1)}requestAnimationFrame(draw)}
 const start=()=>{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume?.();document.getElementById('start-overlay').style.display='none'};
 const reset=()=>{for(const b of [...balls])World.remove(world,b);balls.length=0;particles.length=0;Object.keys(scores).forEach(k=>delete scores[k]);ballAudit.length=0;bossHp=bossMax;document.getElementById('boss-fill').style.width='100%';document.getElementById('boss-hp').textContent='100%';document.getElementById('top-user').textContent='Aguardando drops...';document.getElementById('top-score').textContent='0 PTS'};
 const getState=()=>{const top=Object.entries(scores).sort((a,z)=>z[1]-a[1])[0]||['',0];return{bossHp,bossMaxHp:bossMax,bossPercent:Math.round(bossHp/bossMax*100),activeBalls:balls.length,topUser:top[0],topScore:top[1],viewport:{width:W,height:H}}};
 const getBallAudit=()=>ballAudit.map(x=>({...x}));
 build();draw();return{drop,reset,resize:build,getState,getBallAudit,start,toast};
}
