import {createBallWatchdog} from './ball-watchdog.js';
import {createBallTelemetry} from './ball-telemetry.js';
import {createPinDeflector} from './pin-deflector.js';
import {createPhysics,createFixedStepper} from './physics.js';
import {createRenderer} from './renderer.js';
import {GAME_RULES,slotIndex,slotPoints} from './rules.js';
const {Engine,World,Bodies}=Matter;
const compact=value=>{const n=Math.max(0,Number(value)||0),units=[['B',1e9],['M',1e6],['K',1e3]];for(const [suffix,base] of units)if(n>=base){const v=n/base;return`${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:v<100?1:0}).format(v)}${suffix}`}return new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0}).format(n)};
const displayUser=value=>{const raw=String(value||'').trim();if(!raw)return'Aguardando...';return raw.startsWith('@')?raw:`@${raw}`};
const fitUser=(el,value)=>{if(!el)return;const label=displayUser(value),length=label.length;el.textContent=label;el.dataset.fit=length>22?'xlong':length>16?'long':length>10?'medium':'short'};
export function createGameRuntime({audio}={}){
 let W=innerWidth,H=innerHeight,ballSeq=0,bossHp=GAME_RULES.boss.maxHp;const engine=Engine.create({gravity:{x:0,y:GAME_RULES.gravity,scale:.001}}),world=engine.world,canvas=document.getElementById('fx-canvas'),ctx=canvas.getContext('2d'),balls=[],particles=[],scores={},damageScores={},telemetry=createBallTelemetry();
 const audit=(b,event,data={})=>telemetry.push(b,event,data),sound=t=>audio?.play?.(t);
 const leaders=map=>Object.entries(map).sort((a,z)=>z[1]-a[1])[0]||['',0];
 const updateLeaders=()=>{const points=leaders(scores),damage=leaders(damageScores);fitUser(document.getElementById('top-points-user'),points[0]);fitUser(document.getElementById('top-damage-user'),damage[0]);const pv=document.getElementById('top-points-value'),dv=document.getElementById('top-damage-value');if(pv)pv.textContent=`${compact(points[1])} PTS`;if(dv)dv.textContent=`${compact(damage[1])} DMG`};
 const spark=(x,y,color,count)=>{for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,r:Math.random()*2.5+1,color,a:1})};
 const toast=(text,color='#00f0ff')=>{const f=document.getElementById('toast-feed');if(!f)return;const e=document.createElement('div');e.className='toast-entry';e.style.borderLeftColor=color;e.textContent=text;f.appendChild(e);setTimeout(()=>e.remove(),4000)};
 function damage(dmg,user){const hit=Math.max(0,Number(dmg)||0),name=String(user||'Live');damageScores[name]=(damageScores[name]||0)+hit;updateLeaders();bossHp=Math.max(0,bossHp-hit);const pct=bossHp/GAME_RULES.boss.maxHp*100;document.getElementById('boss-fill').style.width=pct+'%';document.getElementById('boss-hp').textContent=Math.ceil(pct)+'%';sound('boss_hit');const boss=physics.snapshot().boss;if(boss)particles.push({x:boss.position.x,y:boss.position.y,wave:true,r:15,color:'#ff0055',a:1});if(bossHp<=0){bossHp=GAME_RULES.boss.maxHp;document.getElementById('boss-fill').style.width='100%';document.getElementById('boss-hp').textContent='100%';toast(`💥 ${name} FINALIZOU O BOSS!`,'#ffe600');window.confetti?.({particleCount:100,spread:70,origin:{y:.3}})}}
 function finish(b,physicalSlot){if(!b?.gameData||b.gameData.finished||!balls.includes(b))return false;const {slotWidth,slotY}=physics.snapshot(),i=Number.isInteger(physicalSlot)?physicalSlot:slotIndex(b.position.x,W),pts=slotPoints(b.gameData.scoreValue,i);b.gameData.finished=true;b.gameData.slot=i;b.gameData.points=pts;audit(b,'slot',{slot:i,multiplier:GAME_RULES.slots[i],points:pts,durationMs:performance.now()-b.gameData.spawnedAt,pinHits:b.gameData.pinHits||0,deflections:b.gameData.deflections||0,stalls:b.gameData.stalls||0,lastPin:b.gameData.lastPin||null});scores[b.gameData.username]=(scores[b.gameData.username]||0)+pts;updateLeaders();const slot=document.getElementById('slot-'+i);slot?.classList.add('active');setTimeout(()=>slot?.classList.remove('active'),200);spark((i+.5)*slotWidth,slotY,b.gameData.color,10);sound('score');World.remove(world,b);const n=balls.indexOf(b);if(n>=0)balls.splice(n,1);audit(b,'removed',{reason:'scored'});return true}
 const deflect=createPinDeflector({Matter,onDeflect:(ball,pin,data)=>audit(ball,'pin-deflect',{pin:pin.plugin?.pinId||pin.id,...data})});
 const physics=createPhysics({Matter,engine,world,onCollision:e=>e.pairs.forEach(p=>{const a=p.bodyA,b=p.bodyB,labels=[a.label,b.label],ball=a.label==='ball'?a:b;if(!labels.includes('ball'))return;if(labels.includes('pin')){const pin=a.label==='pin'?a:b;telemetry.pinHit(ball,pin);deflect(ball,pin);spark(pin.position.x,pin.position.y,'#00f0ff',3);sound('hit')}if(labels.includes('boss')&&ball.gameData)damage(ball.gameData.damage,ball.gameData.username);if(labels.includes('slotSensor')){const sensor=a.label==='slotSensor'?a:b;finish(ball,sensor.plugin?.slotIndex)}})});
 function resize(){W=Math.max(280,innerWidth);H=Math.max(480,innerHeight);const d=devicePixelRatio||1;canvas.width=Math.round(W*d);canvas.height=Math.round(H*d);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(d,0,0,d,0,0);physics.build(W,H)}
 function drop(opts={}){const {username='Live',color='#00f0ff',radius=9,damage=15,scoreValue=5,density=.002}=opts,spread=W*GAME_RULES.ball.spawnSpread,x=W/2+(Math.random()*spread-spread/2),b=Bodies.circle(x,H*.15,radius,{restitution:GAME_RULES.ball.restitution,friction:GAME_RULES.ball.friction,frictionStatic:GAME_RULES.ball.frictionStatic,frictionAir:GAME_RULES.ball.frictionAir,density,label:'ball',slop:GAME_RULES.ball.slop,collisionFilter:{group:-1}});b.gameData={id:`ball-${++ballSeq}`,username,color,radius,damage,scoreValue,spawnedAt:performance.now(),finished:false,pinHits:0,deflections:0,stalls:0,lastPin:null};balls.push(b);World.add(world,b);audit(b,'spawn',{scoreValue,radius,damage});return b}
 const watchdog=createBallWatchdog({Matter,world,balls,getBounds:()=>{const s=physics.snapshot();return{width:W,height:H,slotY:s.slotY}},onStall:(b,data)=>audit(b,'stall',data),onRemove:(b,reason)=>audit(b,'removed',{reason,durationMs:performance.now()-b.gameData.spawnedAt,pinHits:b.gameData.pinHits||0,lastPin:b.gameData.lastPin||null})}),step=createFixedStepper(engine,Matter),renderer=createRenderer({ctx,getSize:()=>({width:W,height:H}),getBoard:physics.snapshot,balls,particles,Matter});
 function draw(now=performance.now()){step(now);watchdog.tick(now);renderer.frame();requestAnimationFrame(draw)}
 const start=()=>{audio?.unlock?.();document.getElementById('start-overlay').style.display='none'};
 const reset=()=>{for(const b of [...balls])World.remove(world,b);balls.length=0;particles.length=0;Object.keys(scores).forEach(k=>delete scores[k]);Object.keys(damageScores).forEach(k=>delete damageScores[k]);telemetry.clear();bossHp=GAME_RULES.boss.maxHp;document.getElementById('boss-fill').style.width='100%';document.getElementById('boss-hp').textContent='100%';updateLeaders()};
 const getState=()=>{const top=leaders(scores),topDamage=leaders(damageScores),board=physics.snapshot(),pinBottom=board.pins.reduce((max,p)=>Math.max(max,p.position.y+GAME_RULES.board.pinBodyRadius),0);return{bossHp,bossMaxHp:GAME_RULES.boss.maxHp,bossPercent:Math.round(bossHp/GAME_RULES.boss.maxHp*100),activeBalls:balls.length,topUser:top[0],topScore:top[1],topDamageUser:topDamage[0],topDamage:topDamage[1],multipliers:[...GAME_RULES.slots],board:{slotY:board.slotY,pinBottom},viewport:{width:W,height:H},soundEnabled:audio?.isEnabled?.()??true,audio:audio?.status?.()||null}};
 const getBallAudit=()=>telemetry.snapshot();resize();updateLeaders();draw();return{drop,reset,resize,getState,getBallAudit,start,toast};
}
