const {test,expect}=require('@playwright/test');
async function state(page){return page.evaluate(()=>CyberGame.getState())}
async function waitDrain(page,timeout=20000){await expect.poll(async()=>(await state(page)).activeBalls,{timeout,intervals:[250,500]}).toBe(0)}
const events=(audit,name)=>audit.filter(x=>x.event===name);
const drop=(type,user='Bot',quantity=1)=>CyberLiveActions.execute({action:'drop_ball',params:{ballType:type,quantity},user});
test.beforeEach(async({page})=>{await page.goto('/');await page.waitForFunction(()=>window.CyberGame&&window.CyberLiveActions)});

test('2 Galaxias: 2 entram em slots, nenhuma trava, some ou teleporta',async({page})=>{
 await page.evaluate(async()=>{CyberGame.reset();await CyberLiveActions.execute({action:'drop_ball',params:{ballType:'galaxia',quantity:2},user:'TraceBall'})});await waitDrain(page);
 const a=await page.evaluate(()=>CyberGame.getBallAudit()),sp=events(a,'spawn'),sl=events(a,'slot'),rm=events(a,'removed'),hits=events(a,'pin-hit'),def=events(a,'pin-deflect'),stalls=events(a,'stall');
 expect(sp).toHaveLength(2);expect(sl).toHaveLength(2);expect(rm).toHaveLength(2);expect(stalls).toHaveLength(0);expect(new Set(sl.map(x=>x.id)).size).toBe(2);expect(rm.every(x=>x.reason==='scored')).toBeTruthy();
 for(const ball of sp){const end=sl.find(x=>x.id===ball.id),path=hits.filter(x=>x.id===ball.id),out=def.filter(x=>x.id===ball.id);expect(end).toBeTruthy();expect(end.durationMs).toBeGreaterThan(0);expect(end.durationMs).toBeLessThan(20000);expect(end.stalls).toBe(0);expect(end.pinHits).toBe(path.length);expect(out.length).toBeLessThanOrEqual(path.length);if(path.length===0)expect(out).toHaveLength(0);else expect(out.length).toBeGreaterThan(0);expect(Math.abs(end.x-ball.x)).toBeLessThan(page.viewportSize().width);expect(path.every((h,i)=>i===0||h.at>=path[i-1].at)).toBeTruthy()}
});

test('5 bolas completam spawn-slot-remocao e pontuam exatamente uma vez',async({page})=>{await page.evaluate(async()=>{CyberGame.reset();await CyberLiveActions.execute({action:'drop_ball',params:{ballType:'like',quantity:5},user:'FiveBall'})});await waitDrain(page);const r=await page.evaluate(()=>({state:CyberGame.getState(),audit:CyberGame.getBallAudit()})),sp=events(r.audit,'spawn'),sl=events(r.audit,'slot'),rm=events(r.audit,'removed');expect(sp).toHaveLength(5);expect(sl).toHaveLength(5);expect(rm).toHaveLength(5);expect(events(r.audit,'stall')).toHaveLength(0);expect(new Set(sl.map(x=>x.id)).size).toBe(5);expect(rm.every(x=>x.reason==='scored')).toBeTruthy();expect(sl.every(x=>r.state.multipliers[x.slot]===x.multiplier&&x.points===5*x.multiplier)).toBeTruthy();expect(r.state.topScore).toBe(sl.reduce((n,x)=>n+x.points,0))});
test('multiplicadores inferiores seguem 2x 5x 15x 5x 2',async({page})=>{expect((await state(page)).multipliers).toEqual([2,5,15,5,2]);for(let i=0;i<5;i++)await expect(page.locator('#slot-'+i)).toContainText([2,5,15,5,2][i]+'X')});
test('bots simulam partida completa sem acumular ou travar bolas',async({page})=>{await page.evaluate(()=>{CyberGame.reset();for(let i=0;i<36;i++){setTimeout(()=>CyberLiveActions.execute({action:'drop_ball',params:{ballType:'like',quantity:1},user:'BotLike'+i}),i*45);if(i%4===0)setTimeout(()=>CyberLiveActions.execute({action:'drop_ball',params:{ballType:'comment',quantity:1},user:'BotChat'+i}),i*45+15);if(i%9===0)setTimeout(()=>CyberLiveActions.execute({action:'drop_ball',params:{ballType:i%18===0?'capivara':'rosa',quantity:1},user:'BotGift'+i}),i*45+25)}});await page.waitForTimeout(2500);await waitDrain(page,25000);const a=await page.evaluate(()=>CyberGame.getBallAudit()),s=await state(page);expect(s.topScore).toBeGreaterThan(0);expect(events(a,'slot').length).toBeGreaterThan(0);expect(events(a,'stall')).toHaveLength(0)});
test('rajada de presentes: todo spawn cruza um slot e pontua exatamente uma vez',async({page})=>{await page.evaluate(()=>{CyberGame.reset();for(let i=0;i<10;i++)CyberLiveActions.execute({action:'drop_ball',params:{ballType:i%3===0?'galaxia':i%3===1?'capivara':'rosa',quantity:1},user:'Stress'+i})});await page.waitForTimeout(1000);await waitDrain(page,25000);let s=await state(page),a=await page.evaluate(()=>CyberGame.getBallAudit()),sp=events(a,'spawn'),sl=events(a,'slot'),rm=events(a,'removed');expect(sp.length).toBeGreaterThan(0);expect(sl).toHaveLength(sp.length);expect(rm).toHaveLength(sp.length);expect(new Set(sl.map(x=>x.id)).size).toBe(sp.length);expect(rm.every(x=>x.reason==='scored')).toBeTruthy();expect(events(a,'stall')).toHaveLength(0);expect(s.bossPercent).toBeGreaterThan(0);expect(s.bossPercent).toBeLessThanOrEqual(100);await page.evaluate(()=>CyberLiveActions.execute({action:'drop_ball',params:{ballType:'like',quantity:1},user:'AfterStress'}));await expect.poll(async()=>(await state(page)).activeBalls,{timeout:2000}).toBeGreaterThan(0);await waitDrain(page)});
test('resize durante partida nao deixa corpos orfaos nem stall',async({page})=>{await page.evaluate(()=>{CyberGame.reset();CyberLiveActions.execute({action:'drop_ball',params:{ballType:'like',quantity:12},user:'ResizeBot'})});await page.setViewportSize({width:390,height:700});await page.evaluate(()=>CyberGame.resize());await waitDrain(page,25000);expect(events(await page.evaluate(()=>CyberGame.getBallAudit()),'stall')).toHaveLength(0)});
