const {test,expect}=require('@playwright/test');
async function state(page){return page.evaluate(()=>CyberGame.getState())}
async function waitDrain(page,timeout=25000){await expect.poll(async()=>(await state(page)).activeBalls,{timeout,intervals:[500,1000]}).toBe(0)}
test.beforeEach(async({page})=>{await page.goto('/');await page.waitForFunction(()=>window.CyberGame&&window.CyberLiveActions)});
test('2 bolas: ambas caem fisicamente, sem sumir/teleportar, com trilha de pinos',async({page})=>{await page.evaluate(()=>{CyberGame.reset();CyberGame.triggerGift('TraceBall','Galáxia');CyberGame.triggerGift('TraceBall','Galáxia')});await waitDrain(page,25000);const a=await page.evaluate(()=>CyberGame.getBallAudit()),sp=a.filter(x=>x.event==='spawn'),sl=a.filter(x=>x.event==='slot'),rm=a.filter(x=>x.event==='removed'),hits=a.filter(x=>x.event==='pin-hit');expect(sp).toHaveLength(2);expect(sl).toHaveLength(2);expect(rm).toHaveLength(2);expect(new Set(sl.map(x=>x.id)).size).toBe(2);expect(rm.every(x=>x.reason==='scored')).toBeTruthy();for(const ball of sp){const end=sl.find(x=>x.id===ball.id),path=hits.filter(x=>x.id===ball.id);expect(end).toBeTruthy();expect(end.durationMs).toBeGreaterThan(0);expect(end.durationMs).toBeLessThan(25000);expect(end.pinHits).toBe(path.length);expect(end.lastPin??null).toBe(path.at(-1)?.pin??null);expect(Math.abs(end.x-ball.x)).toBeLessThan(page.viewportSize().width);expect(path.every((h,i)=>i===0||h.at>=path[i-1].at)).toBeTruthy()}});
test('5 bolas completam spawn-slot-remocao e pontuam exatamente uma vez',async({page})=>{await page.evaluate(()=>{CyberGame.reset();for(let i=0;i<5;i++)CyberGame.triggerLike('FiveBall')});await waitDrain(page);const r=await page.evaluate(()=>({state:CyberGame.getState(),audit:CyberGame.getBallAudit()})),sp=r.audit.filter(x=>x.event==='spawn'),sl=r.audit.filter(x=>x.event==='slot'),rm=r.audit.filter(x=>x.event==='removed');expect(sp).toHaveLength(5);expect(sl).toHaveLength(5);expect(rm).toHaveLength(5);expect(new Set(sl.map(x=>x.id)).size).toBe(5);expect(rm.every(x=>x.reason==='scored')).toBeTruthy();expect(sl.every(x=>r.state.multipliers[x.slot]===x.multiplier&&x.points===5*x.multiplier)).toBeTruthy();expect(r.state.topScore).toBe(sl.reduce((n,x)=>n+x.points,0))});
test('multiplicadores inferiores seguem 2x 5x 15x 5x 2',async({page})=>{expect((await state(page)).multipliers).toEqual([2,5,15,5,2]);for(let i=0;i<5;i++)await expect(page.locator('#slot-'+i)).toContainText([2,5,15,5,2][i]+'X')});
test('bots simulam partida completa sem acumular bolas',async({page})=>{await page.evaluate(()=>{CyberGame.reset();for(let i=0;i<36;i++){setTimeout(()=>CyberGame.triggerLike('BotLike'+i),i*45);if(i%4===0)setTimeout(()=>CyberGame.triggerComment('BotChat'+i,'!drop'),i*45+15);if(i%9===0)setTimeout(()=>CyberGame.triggerGift('BotGift'+i,i%18===0?'Capivara':'Rosa'),i*45+25)}});await page.waitForTimeout(2500);await waitDrain(page,30000);const s=await state(page);expect(s.topScore).toBeGreaterThan(0);expect(await page.evaluate(()=>CyberGame.getBallAudit().filter(x=>x.event==='slot').length)).toBeGreaterThan(0)});
test('rajada de presentes drena todas as bolas e continua responsivo',async({page})=>{await page.evaluate(()=>{CyberGame.reset();for(let i=0;i<10;i++)CyberGame.triggerGift('Stress'+i,i%3===0?'Galáxia':i%3===1?'Capivara':'Rosa')});await page.waitForTimeout(1000);await waitDrain(page,30000);let s=await state(page);expect(s.bossPercent).toBeGreaterThan(0);expect(s.bossPercent).toBeLessThanOrEqual(100);await page.evaluate(()=>CyberGame.triggerLike('AfterStress'));await expect.poll(async()=>(await state(page)).activeBalls,{timeout:2000}).toBeGreaterThan(0);await waitDrain(page)});
test('resize durante partida nao deixa corpos orfaos',async({page})=>{await page.evaluate(()=>{CyberGame.reset();for(let i=0;i<12;i++)CyberGame.triggerLike('ResizeBot'+i)});await page.setViewportSize({width:390,height:700});await page.evaluate(()=>CyberGame.resize());await waitDrain(page,30000)});
