const $=id=>document.getElementById(id);
const text=(v,fallback='')=>String(v??fallback);
function safeImage(raw){try{const u=new URL(text(raw),location.href);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return''}}
function ruleAction(rule){return text(rule.actionId||rule.action||rule.command)}
function params(rule){return rule.params||rule.actionParams||rule.effectParams||{}}
function giftName(rule){return text(rule.giftName||rule.triggerName||rule.gift?.name||rule.gift?.title,'Presente')}
function giftIcon(rule){return safeImage(rule.giftIcon||rule.giftImage||rule.gift?.icon||rule.gift?.image||rule.gift?.imageUrl)}
function effect(rule){const p=params(rule);if(ruleAction(rule)==='drop_ball'){const q=Math.max(1,Number(p.quantity)||1);return `${q}× bolinha · ${text(p.ballType,'like')}`}if(ruleAction(rule)==='restart')return'Reiniciar partida';return ruleAction(rule)||'Ação'}
export function createLiveHud(){let rules=[];const root=$('live-interactions'),list=$('live-interactions-list');function render(){if(!root||!list)return;list.replaceChildren();if(!rules.length){const empty=document.createElement('div');empty.className='live-rule-empty';empty.textContent='Aguardando regras do painel';list.appendChild(empty);return}for(const rule of rules){const card=document.createElement('article');card.className='live-rule-card';const icon=document.createElement('div');icon.className='live-rule-icon';const src=giftIcon(rule);if(src){const img=document.createElement('img');img.src=src;img.alt='';img.referrerPolicy='no-referrer';icon.appendChild(img)}else icon.textContent='🎁';const copy=document.createElement('div');copy.className='live-rule-copy';const b=document.createElement('b');b.textContent=giftName(rule);const small=document.createElement('small');small.textContent=effect(rule);copy.append(b,small);card.append(icon,copy);list.appendChild(card)}}function setRules(next){rules=Array.isArray(next)?next.filter(r=>r&&ruleAction(r)):[];render();return true}function setVisible(visible){if(root)root.hidden=!visible;try{localStorage.setItem('cyber-live-hud-visible',visible?'1':'0')}catch{}return visible}function toggle(){return setVisible(root?.hidden===true)}try{if(localStorage.getItem('cyber-live-hud-visible')==='0'&&root)root.hidden=true}catch{}render();return{setRules,setVisible,toggle,getRules:()=>rules.map(r=>({...r}))}}
